# Generated by Django 5.1.5 on 2025-01-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_aditivo_dias_alter_aditivo_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='melhor_dia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
