# Generated by Django 5.1.5 on 2025-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_maodeobra_valor_reembolso'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
