# Generated by Django 5.1.5 on 2025-01-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_cartao_melhor_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='adiantamento',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
        migrations.AlterField(
            model_name='aditivo',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
        migrations.AlterField(
            model_name='bm',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
        migrations.AlterField(
            model_name='notaboleto',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
        migrations.AlterField(
            model_name='notapix',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
    ]
