# Generated by Django 5.1.5 on 2025-02-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_funcionario_custo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacartao',
            name='contador_parcelas',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notacartao',
            name='proximo_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
