# Generated by Django 5.1.5 on 2025-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_banco_alter_adiantamento_banco_alter_aditivo_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='banco',
            field=models.CharField(max_length=100),
        ),
    ]
