# Generated by Django 5.1.5 on 2025-02-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_notacartao_contador_parcelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacartao',
            name='status_parcelamento',
            field=models.CharField(choices=[('a_pagar', 'À pagar'), ('pago', 'Pago')], default='a_pagar', max_length=20),
            preserve_default=False,
        ),
    ]
