# Generated by Django 5.1.5 on 2025-02-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_notacartao_status_parcelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='notacartao',
            name='parcelas_pagamento',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='notacartao',
            name='status_parcelamento',
            field=models.CharField(choices=[('a_pagar', 'À pagar'), ('pago', 'Pago')], default='a_pagar', max_length=20),
        ),
    ]
