# Generated by Django 5.1.5 on 2025-01-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_cartao_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
    ]
