# Generated by Django 5.1.5 on 2025-02-05 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_notacartao_parcelas_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacartao',
            name='parcelas_pagamento',
        ),
        migrations.AlterField(
            model_name='notacartao',
            name='status_parcelamento',
            field=models.CharField(choices=[('a_pagar', 'À pagar'), ('pago', 'Pago')], max_length=20),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota_cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.notacartao')),
            ],
        ),
    ]
