# Generated by Django 5.1.5 on 2025-01-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_alter_cartao_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='logo_path',
            field=models.CharField(blank=True, default='assets/bancosLogo/default_logo.png', max_length=255),
        ),
    ]
