# Generated by Django 5.1.5 on 2025-02-06 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_remove_notacartao_parcelas_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notacartao',
            name='contador_parcelas',
        ),
        migrations.RemoveField(
            model_name='notacartao',
            name='proximo_pagamento',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='nota_cartao',
        ),
        migrations.AlterField(
            model_name='notacartao',
            name='quant_parcelas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('a_pagar', 'À pagar'), ('pago', 'Pago')], max_length=20)),
                ('nota_cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='financeiro.notacartao')),
            ],
        ),
        migrations.AddField(
            model_name='pagamento',
            name='parcela',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='financeiro.parcela'),
            preserve_default=False,
        ),
    ]
