# Generated by Django 5.1.5 on 2025-01-23 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_banco_logo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='vencimento',
            field=models.IntegerField(help_text='Insira um número entre 1 e 31', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
