# Generated by Django 5.1.5 on 2025-02-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0008_remove_notacartao_contador_parcelas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('cartao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.cartao')),
            ],
        ),
    ]
