# Generated by Django 5.1.5 on 2025-02-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_fatura_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
