# Generated by Django 5.1.5 on 2025-02-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0011_fatura_observacao'),
        ('locais', '0003_obra_escritorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='escritorio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='locais.escritorio'),
            preserve_default=False,
        ),
    ]
