# Generated by Django 5.1.5 on 2025-02-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_cartao_escritorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='modalidadeEscritorio',
            field=models.CharField(blank=True, choices=[('imposto', 'Imposto'), ('contador', 'Contador'), ('rastreamento', 'Rastreamento'), ('parcela_carro', 'Parcela do carro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('mao_de_obra', 'Mão de Obra'), ('insumos', 'Insumos'), ('combustivel', 'Combustível')], max_length=50, null=True),
        ),
    ]
