# Generated by Django 5.1.5 on 2025-03-05 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_despesa_modalidadeescritorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aditivo',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
    ]
