# Generated by Django 5.1.5 on 2025-03-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0014_alter_aditivo_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
