# Generated by Django 5.1.5 on 2025-03-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0015_alter_fatura_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartao',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
