# Generated by Django 5.1.5 on 2025-03-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0016_cartao_imagem_url_cartao_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='imagem_url',
        ),
        migrations.RemoveField(
            model_name='cartao',
            name='public_id',
        ),
        migrations.AddField(
            model_name='banco',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
