# Generated by Django 5.1.5 on 2025-03-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0017_remove_banco_logo_path_remove_cartao_imagem_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='cor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
