# Generated by Django 5.1.5 on 2025-03-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0018_cartao_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='cor',
            field=models.CharField(blank=True, default='zinc', max_length=30),
        ),
    ]
