# Generated by Django 5.1.5 on 2025-03-13 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0019_alter_cartao_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaboleto',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
        migrations.AlterField(
            model_name='notaboleto',
            name='num_notafiscal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notaboleto',
            name='recipiente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
