# Generated by Django 5.1.5 on 2025-03-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0020_alter_notaboleto_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('mao_de_obra', 'Mão de Obra'), ('insumos', 'Insumos'), ('combustivel', 'Combustível'), ('administracao', 'Administração'), ('outra', 'Outra')], max_length=50, null=True),
        ),
    ]
