# Generated by Django 5.1.5 on 2025-03-13 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0021_alter_despesa_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financeiro.banco'),
        ),
    ]
