# Generated by Django 5.1.5 on 2025-01-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cargo',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('FUNC', 'Funcionário')], default='ADM', max_length=4),
            preserve_default=False,
        ),
    ]
