# Generated by Django 5.1.5 on 2025-02-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cargo',
        ),
    ]
