# Generated by Django 5.1.5 on 2025-01-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=18)),
                ('ceo', models.CharField(max_length=100)),
                ('debito_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debito_geral', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField(blank=True, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_receber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debito_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debito_geral', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo_inicial', models.DateField()),
                ('prazo_atual', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
