# Generated by Django 5.1.5 on 2025-02-10 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_alter_obra_custo_total_alter_obra_debito_geral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='escritorio',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='obras', to='locais.escritorio'),
            preserve_default=False,
        ),
    ]
