# Generated by Django 5.1.5 on 2025-02-10 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0003_obra_escritorio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_escritorio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escritorio',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, related_name='funcionarios_escritorio', to=settings.AUTH_USER_MODEL),
        ),
    ]
