# Generated by Django 5.1.5 on 2025-02-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0005_remove_escritorio_ceo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritorio',
            name='debito_geral',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
        migrations.AlterField(
            model_name='escritorio',
            name='debito_mensal',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
