# Generated by Django 5.1.5 on 2025-02-11 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0006_alter_escritorio_debito_geral_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escritorio',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='membros', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AcessoEscritorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('ADM', 'Administrador'), ('FUNC', 'Funcionário')], max_length=4)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pending', max_length=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('escritorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escritorio', to='locais.escritorio')),
                ('user_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_receptor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
