# Generated by Django 5.1.5 on 2025-02-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0007_escritorio_membros_acessoescritorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessoescritorio',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=10),
        ),
    ]
