# Generated by Django 5.1.5 on 2025-03-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0008_alter_acessoescritorio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
