# Generated by Django 5.1.5 on 2025-03-05 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0009_obra_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='image_url',
            new_name='imagem_url',
        ),
    ]
