# Generated by Django 5.1.5 on 2025-03-05 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0010_rename_image_url_obra_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
